import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import Card from '../components/card';
import styles from '../styles/Home.module.css';
import coffeeStores from '../data/coffee-stores.json';


//this is a server side code
export async function getStaticProps(context) {
  //Note normally this is where we do fetch e.g const data=fetch(url).then(res->response.json()) etc and we put the data instead of the coffeeStores
  return {
    props: {
      coffeeStores
    }, // will be passed to the page component as props
  }
}

//after that we pass a props to the Home function which will contain the data from getStaticProps
//this is a client side code
export default function Home(props) {
  console.log('props', props.coffeeStores)
	const handleOnClick = () => {
		console.log('hi banner button clicked');
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner buttonText="View stores nearby" handleOnClick={handleOnClick} />

				<div className={styles.heroImage}>
					<Image src="/static/hero-image.png" width={700} height={400} />
				</div>
       {props.coffeeStores.length > 0 &&
       <>
          <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl}
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                  coffee={coffeeStore}
                />
              ))}
            </div>
        </>
        } 
			</main>
		</div>
	);
}
